run:
  timeout: 5m
linters:
  enable:
  - bodyclose
  - gofmt
  - importas
  - loggercheck
  - noctx
  - prealloc
  - revive
  - unparam
  - usestdlibvars
  - errorlint
  - misspell
  - unconvert
  - perfsprint
  - mirror
  - wsl
  - copyloopvar
  - gci
linters-settings:
  govet:
    enable:
    - nilness
    - unusedwrite
  gci:
    sections:
      - standard
      - default
      - localmodule
    custom-order: true
