run:
  timeout: 5m
linters:
  enable:
  - bodyclose
  - exportloopref
  - gofmt
  - importas
  - loggercheck
  - noctx
  - prealloc
  - revive
  - unparam
  - usestdlibvars
  - errorlint
  - misspell
  - unconvert
  - perfsprint
  - mirror
  - wsl
  - copyloopvar
linters-settings:
  govet:
    enable:
    - nilness
    - unusedwrite
