name: build

on:
  push:
    branches:
    - '**'
    tags:
    - v[0-9]+.[0-9]+.[0-9]+
  pull_request:

env:
  REGISTRY_IMAGE: ghcr.io/zlabjp/nghttpx-ingress-controller

jobs:
  build:

    runs-on: ubuntu-22.04

    strategy:
      matrix:
        os: [linux]
        arch: [amd64, arm64]

    steps:
    - uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    - uses: golangci/golangci-lint-action@v4
      with:
        skip-pkg-cache: true
        skip-build-cache: true
    - name: Build
      run: |
        make vet check controller
      env:
        GOOS: ${{ matrix.os }}
        GOARCH: ${{ matrix.arch }}
    - name: Resolve image properties
      uses: actions/github-script@v7
      id: imageprops
      with:
        script: |
          core.setOutput('push', '${{ github.ref_type }}' == 'tag' || '${{ github.ref_name }}' == 'main')
          core.setOutput('tag', '${{ github.ref_type }}' == 'tag' ? '${{ github.ref_name }}' : 'latest')
    - name: Docker meta
      uses: docker/metadata-action@v5
      id: meta
      with:
        images: ${{ env.REGISTRY_NAME }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build container image
      uses: docker/build-push-action@v5
      id: image-build
      with:
        context: .
        outputs: type=image,name=${{ env.REGISTRY_IMAGE }},push-by-digest=true,name-canonical=true,push=true
        labels: ${{ steps.meta.outputs.labels }}
        provenance: false
        platforms: ${{ matrix.os }}/${{ matrix.arch }}
    - name: Export digest
      run: |
        mkdir -p /tmp/digests
        digest="${{ steps.image-build.outputs.digest }}"
        touch "/tmp/digests/${digest#sha256:}"
    - name: Upload digest
      uses: actions/upload-artifact@v4
      with:
        name: digests-${{ matrix.os }}-${{ matrix.arch }}
        path: /tmp/digests/*
        if-no-files-found: error
        retention-days: 1

  merge:

    runs-on: ubuntu-22.04

    needs:
    - build

    steps:
    - name: Download digests
      uses: actions/download-artifact@v4
      with:
        path: /tmp/digests
        pattern: digests-*
        merge-multiple: true
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Docker meta
      uses: docker/metadata-action@v5
      id: meta
      with:
        images: ${{ env.REGISTRY_IMAGE }}
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - run: |
        echo -n "$DOCKER_METADATA_OUTPUT_JSON"
    - name: Create manifest list and push
      working-directory: /tmp/digests
      run: |
        docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
          $(printf '${{ env.REGISTRY_IMAGE }}@sha256:%s ' *)
    - name: Inspect image
      run: |
        docker buildx imagetools inspect ${{ env.REGISTRY_IMAGE }}:${{ steps.meta.outputs.version }}
