name: build

on:
  push:
    branches:
    - '**'
    tags:
    - v[0-9]+.[0-9]+.[0-9]+
  pull_request:

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '1.20'
        cache: true
    - name: Build
      run: |
        make vet check controller
    - name: Resolve image properties
      uses: actions/github-script@v6
      id: imageprops
      with:
        script: |
          core.setOutput('push', '${{ github.ref_type }}' == 'tag' || '${{ github.ref_name }}' == 'main')
          core.setOutput('tag', '${{ github.ref_type }}' == 'tag' ? '${{ github.ref_name }}' : 'latest')
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      if: steps.imageprops.outputs.push == 'true'
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build container image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: ${{ steps.imageprops.outputs.push == 'true' }}
        tags: zlabjp/nghttpx-ingress-controller:${{ steps.imageprops.outputs.tag }}
        provenance: false
