name: build

on: push

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.15'
    - name: Setup go modules cache
      uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
    - name: Build
      run: |
        make vet check controller
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build docker image (latest)
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      uses: docker/build-push-action@v2
      with:
        context: .
        push: ${{ github.ref == 'refs/heads/main' }}
        tags: zlabjp/nghttpx-ingress-controller:latest
    - name: Output tag name
      id: tag
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        echo "::set-output name=name::${GITHUB_REF#refs/tags/}"
    - name: Build docker image (tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: zlabjp/nghttpx-ingress-controller:${{ steps.tag.outputs.name }}
